apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
  {{- else }}
  username: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
