replicas: 3
profile: dev

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

image:
  repository: busybox
  tag: stable

ports:
  - name: api
    port: 8080
    path: /api
  - name: logs
    port: 8081
    path: /logs
  - name: soap
    port: 8082
    path: /soap

host: dev.inpost.pl
